# Generated by Django 2.2 on 2022-09-04 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Itemprices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itempriceID', models.CharField(blank=True, max_length=220)),
                ('price', models.FloatField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Link',
            new_name='Item',
        ),
        migrations.DeleteModel(
            name='Itemprice',
        ),
        migrations.AddField(
            model_name='itemprices',
            name='name',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='tracker.Item'),
        ),
    ]
